[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
	"imodelsx>=1.0.11",
	"interpret>=0.7.4",
	"matplotlib>=3.10.8",
	"openml>=0.15.1",
	"sparse-transform>=0.2.1",
	"amlt>=10.16.5",
	"tabicl>=0.1.4",
	"tabpfn>=6.3.1",
]

[tool.uv.sources]
amlt = { index = "msr" }

[[tool.uv.index]]
name = "msr"
url = "https://msrpypi.azurewebsites.net/stable/leloojoo"


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
